name: Create Tag

on:
  push:
    branches: [main]

concurrency: create-tag

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get-solution-version
        uses: microsoft-power-platform-ce/actions/get-solution-version@main
      - id: check-for-new-version
        name: Check if committed version already has a tag
        run: |
          Write-Host "::set-output name=is-new-version::$(
            -Not $(
              $(
                git ls-remote --tags origin |
                  ForEach-Object { $_ -Replace "^[^`\s]*`\s*refs/tags/", "" }
              ) ?? [string]::Empty).Contains(
                "v${{ steps.get-solution-version.outputs.solution-version }}"
              )
            )
          )"
        shell: pwsh
      - if: steps.check-for-new-version.outputs.is-new-version == 'True'
        name: Create Tag
        run: |
          git tag v${{ steps.get-solution-version.outputs.solution-version }}
          git push --tags
 